language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

cache:
  directories:
    - vendor

install:
  # Add custom php.ini file if not HHVM
  - 'if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then phpenv config-add build/ci/php.ini; fi'
  - composer install
  # Don't download Box if HHVM because we won't build PHAR file
  - 'if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then wget https://github.com/box-project/box2/releases/download/2.5.0/box-2.5.0.phar; mv box-2.5.0.phar box.phar; fi'

script:
  - make check
  - make test
  # Can't build PHAR file on HHVM because can't set custom PHP settings
  - 'if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then make phar; fi'
