language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

cache:
  directories:
    - vendor

before_script:
  - composer install

script:
  - bin/phpunit -c phpunix.xml.dist
  - bin/phpcs --standard=psr2 bin/projectlint src/ tests/
  - bin/projectlint
