language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

cache:
  directories:
    - vendor

before_script:
  # Make sure PHP conf.d directory exists because it's missing on HHVM boxes
  - "[ -d ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d ] || mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d"
  - phpenv config-add build/ci/projectlint.ini
  - composer install
  - wget https://github.com/cbednarski/pharcc/releases/download/v0.2.3/pharcc.phar

script:
  - make check
  - make test
  - make phar
