language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

cache:
  directories:
    - vendor

before_script:
  - composer install
  - wget https://github.com/cbednarski/pharcc/releases/download/v0.2.3/pharcc.phar

script:
  - make check
  - make test
  - make phar
  - php projectlint.phar
